AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: bhargav-alm-sam-demo
Parameters:
    BucketName:
        Type: String
    CodeKey:
        Type: String
    version:
        Type: String

Resources:
  cybagealmbhargavlambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri:
                # !Ref function allows you to fetch value 
                # of parameters and other resources at runtime
         Bucket: !Ref BucketName
         Key: !Ref CodeKey
      Description: bhargav-alm-sam-demo
      MemorySize: 128
      Timeout: 3
      Version : !Ref version
      Role: 'arn:aws:iam::543816070942:role/lambda_basic_execution'
      Events:
        SNS1:
          Type: SNS
          Properties:
            Topic:
              Ref: SNSTopic1
  SNSTopic1:
    Type: 'AWS::SNS::Topic'
    Properties:
      DisplayName: block/allow
      TopicName: cybage-alm-bhargav-sns
