AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: bhargav-alm-sam-demo
Resources:
  cybagealmbhargavsamcybagealmbhargavssm2SG5I6JLNR9U:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: s3://cybage-alm-bhargav-ssm/cybage-alm-bhargav-sam-${BUILD_NUMBER}.zip
      Description: bhargav-alm-sam-demo
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::543816070942:role/lambda_basic_execution'
      Events:
        SNS1:
          Type: SNS
          Properties:
            Topic:
              Ref: SNSTopic1
  SNSTopic1:
    Type: 'AWS::SNS::Topic'
    Properties:
      DisplayName: block/allow
      TopicName: cybage-alm-bhargav-sns
